spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://15.164.234.108:3306/review?serverTimezone=Asia/Seoul
#    url: jdbc:mysql://localhost:3306/review?serverTimezone=Asia/Seoul
#    username: root
    username: min
    password: 113706

  data:
    redis:
      repositories:
        enabled: false
      host: redis-elasticcache.vjzb0s.ng.0001.apn2.cache.amazonaws.com
      port: 6379

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
    #  ddl-auto: validate
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true



server:
  port: 8080
  address: 0.0.0.0



logging:
  level:
    org.springframework.security: trace
    com.zaxxer.hikari: debug

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

