spring:
  profiles:
    group:
      local:
        - localdb
      test:
    active: local

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/online?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: 113706
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    open-in-view: false
#    properties:
#      hibernate:
#        format_sql: true
#
#logging:
#  level:
#    org.hibernate.SQL: debug